export const FETCH_VILLAGE_START = "FETCH_VILLAGE_START";
export const FETCH_VILLAGE_END = "FETCH_VILLAGE_END";
export const FETCH_VILLAGE_ERROR = "FETCH_VILLAGE_ERROR";
export const ADD_SMURF_START = "ADD_SMURF_START";
export const ADD_SMURF_END = "ADD_SMURF_END";
export const ADD_SMURF_ERROR = "ADD_SMURF_ERROR";